require('dotenv').config()

const IS_DEVELOPMENT = process.env.IS_DEVELOPMENT
const PROXY_URL = process.env.PROXY_URL
const XSS_DETECTION_ENABLED = process.env.XSS_DETECTION_ENABLED
const XSS_CONFIDENCE_FACTOR = process.env.XSS_CONFIDENCE_FACTOR
const SKIP_SSL_VERIFICATION = process.env.SKIP_SSL_VERIFICATION;
const MAX_BODY_PAYLOAD = process.env.MAX_BODY_PAYLOAD;
const UPLOAD_FILE_ENABLED = process.env.UPLOAD_FILE_ENABLED;
const GLOBAL_TIMEOUT = process.env.GLOBAL_TIMEOUT;
const URI_MAX_LENGTH = process.env.URI_MAX_LENGTH;
const CHECK_CONTRACTS_ENABLED = process.env.CHECK_CONTRACTS_ENABLED;
const TO_MANY_REQUEST_MESSAGE = process.env.TO_MANY_REQUEST_MESSAGE;
const TO_MANY_REQUEST_TIME = process.env.TO_MANY_REQUEST_TIME;
const CONTRACT_NOT_SATISFY_ORIGIN_MESSAGE = process.env.CONTRACT_NOT_SATISFY_ORIGIN_MESSAGE;
const REQUEST_USER_HAS_INVALID_ROLE_MESSAGE = process.env.REQUEST_USER_HAS_INVALID_ROLE_MESSAGE;
const CONTRACT_NOT_FOUND_MESSAGE = process.env.CONTRACT_NOT_FOUND_MESSAGE;
const XSS_ATTACK_ERROR_MESSAGE = process.env.XSS_ATTACK_ERROR_MESSAGE;
const CHECK_FILTERING_ENABLED = process.env.CHECK_FILTERING_ENABLED;
const DEFAULT_ADMIN_USERNAME = process.env.DEFAULT_ADMIN_USERNAME;
const DEFAULT_ADMIN_PASSWORD = process.env.DEFAULT_ADMIN_PASSWORD;
const DATABASE_CONNECTION_STRING = process.env.DATABASE_CONNECTION_STRING;
const ADMIN_PANEL_SESSION_SECRET = process.env.ADMIN_PANEL_SESSION_SECRET;
const ADMIN_PANEL_COOKIE_SECRET = process.env.ADMIN_PANEL_COOKIE_SECRET;
const CORS_URL = process.env.CORS_URL;
const PORT = process.env.PORT;
const ZIP_LOG_FILES_LIMIT = process.env.ZIP_LOG_FILES_LIMIT;
const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;

module.exports = {
      IS_DEVELOPMENT,
      JWT_SECRET_KEY,
      ZIP_LOG_FILES_LIMIT,
      PORT,
      ADMIN_PANEL_COOKIE_SECRET,
      CORS_URL,
      ADMIN_PANEL_SESSION_SECRET,
      CHECK_FILTERING_ENABLED,
      DATABASE_CONNECTION_STRING,
      DEFAULT_ADMIN_USERNAME,
      DEFAULT_ADMIN_PASSWORD,
      PROXY_URL,
      CONTRACT_NOT_FOUND_MESSAGE,
      CONTRACT_NOT_SATISFY_ORIGIN_MESSAGE,
      XSS_ATTACK_ERROR_MESSAGE,
      REQUEST_USER_HAS_INVALID_ROLE_MESSAGE,
      XSS_DETECTION_ENABLED,
      URI_MAX_LENGTH,
      TO_MANY_REQUEST_MESSAGE,
      TO_MANY_REQUEST_TIME,
      XSS_CONFIDENCE_FACTOR,
      CHECK_CONTRACTS_ENABLED,
      SKIP_SSL_VERIFICATION,
      UPLOAD_FILE_ENABLED,
      GLOBAL_TIMEOUT,
      MAX_BODY_PAYLOAD
}